language: php

dist: xenial

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  include:
    php:
      - 7.1
      - 7.2
      - 7.3
      - 7.4

install:
  - composer install --no-interaction --no-progress --no-suggest --prefer-dist

script:
  - vendor/bin/phpunit ./tests
